### ISSUE TITLE
sporadic NullReferenceExceptions crashing the analyzer

### ISSUE THREAD

**Issue by milleniumbug** [JohanLarsson/Gu.Analyzers#71]
From time to time, a NullReferenceException is thrown from the analyzer, but unfortunately these happen not that often and they're hard to reproduce. 

```
Severity    Code    Description Project File    Line    Suppression State   Detail Description
Warning AD0001  Analyzer 'Gu.Analyzers.GU0032DisposeBeforeReassigning' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. TaxonomyWpf     1   Active  Analyzer 'Gu.Analyzers.GU0032DisposeBeforeReassigning' threw the following exception:
'Exception occurred with following context:
Compilation: Taxonomy
SyntaxTree: C:\Users\milleniumbug\Desktop\Taxonomy\TaxonomyWpf\IndexedList.cs
SyntaxNode: decorated[index] = value [AssignmentExpressionSyntax]@[1787..1811) (80,4)-(80,28)
 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gu.Analyzers.Disposable.Classification.Check(ExpressionSyntax disposable, SemanticModel semanticModel, CancellationToken cancellationToken, HashSet`1 checked, List`1 classifications)
   at Gu.Analyzers.Disposable.Classification.Create(ExpressionSyntax disposable, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Gu.Analyzers.Disposable.IsPotentialCreation(ExpressionSyntax disposable, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Gu.Analyzers.GU0032DisposeBeforeReassigning.HandleAssignment(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

the source file I was editing at the time (I *think* the crash happened after I pressed the dot key on the keyboard to type in `Value` in the indexer setter, but I'm not 100% sure):

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TaxonomyWpf
{
	public class IndexedList<T> : IList<KeyValuePair<int, T>>
	{
		protected IList<T> decorated;

		public IndexedList(IList<T> decorated)
		{
			if(decorated == null)
				throw new ArgumentNullException(nameof(decorated));

			this.decorated = decorated;
		}

		public IEnumerator<KeyValuePair<int, T>> GetEnumerator()
		{
			return decorated.Select((element, index) => new KeyValuePair<int, T>(index, element)).GetEnumerator();
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		void ICollection<KeyValuePair<int, T>>.Add(KeyValuePair<int, T> item)
		{
			Add(item.Value);
		}

		public void Add(T item)
		{
			decorated.Add(item);
		}

		public void Clear()
		{
			decorated.Clear();
		}

		bool ICollection<KeyValuePair<int, T>>.Contains(KeyValuePair<int, T> item)
		{
			return Contains(item.Value);
		}

		public bool Contains(T item)
		{
			return decorated.Contains(item);
		}

		public void CopyTo(KeyValuePair<int, T>[] array, int arrayIndex)
		{
			throw new NotImplementedException();
		}

		public bool Remove(KeyValuePair<int, T> item)
		{
			return decorated.Remove(item.Value);
		}

		public int Count => decorated.Count;
		public bool IsReadOnly => decorated.IsReadOnly;

		public int IndexOf(KeyValuePair<int, T> item)
		{
			return decorated.IndexOf(item.Value);
		}

		void IList<KeyValuePair<int, T>>.Insert(int index, KeyValuePair<int, T> item)
		{
			Insert(index, item.Value);
		}

		public void Insert(int index, T item)
		{
			decorated.Insert(index, item);
		}

		public void RemoveAt(int index)
		{
			decorated.RemoveAt(index);
		}
		public KeyValuePair<int, T> this[int index]
		{
			get { return new KeyValuePair<int, T>(index, decorated[index]); }
			set { decorated[index] = value.Value; }
		}
	}

	public class ObservableIndexedList<T> : IndexedList<T>, INotifyCollectionChanged
	{
		public ObservableIndexedList(ObservableCollection<T> decorated) : 
			base(decorated)
		{

		}

		public event NotifyCollectionChangedEventHandler CollectionChanged
		{
			add { ((ObservableCollection<T>)decorated).CollectionChanged += value; }
			remove { ((ObservableCollection<T>)decorated).CollectionChanged -= value; }
		}
	}
}
```

**Comment by milleniumbug** [comment]
another one:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'WpfAnalyzers.PropertyChanged.WPF1014DontRaiseChangeForMissingProperty' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	TaxonomyWpf		1	Active	Analyzer 'WpfAnalyzers.PropertyChanged.WPF1014DontRaiseChangeForMissingProperty' threw the following exception:
'Exception occurred with following context:
Compilation: Taxonomy
SyntaxTree: C:\Users\milleniumbug\Desktop\Taxonomy\TaxonomyWpf\BreadCrumbs.xaml.cs
SyntaxNode: OnPropertyChanged() [InvocationExpressionSyntax]@[1574..1593) (61,3)-(61,22)

System.NullReferenceException: Object reference not set to an instance of an object.
   at WpfAnalyzers.PropertyChanged.WPF1014DontRaiseChangeForMissingProperty.HandleInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

the code:

```
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;

namespace TaxonomyWpf
{
	public enum Mode
	{
		BreadCrumbs,
		Editing
	}

	/// <summary>
	/// Interaction logic for BreadCrumbs.xaml
	/// </summary>
	public partial class BreadCrumbs : UserControl, INotifyPropertyChanged
	{
		public ObservableCollection<KeyValuePair<int, string>> Components { get; }

		private Mode mode;

		public Mode Mode
		{
			get { return mode; }
			set { mode = value; OnPropertyChanged(); }
		}

		public static readonly DependencyProperty PathProperty = DependencyProperty.Register(
			nameof(Path),
			typeof(string),
			typeof(BreadCrumbs),
			new PropertyMetadata(default(string), OnPathChanged, CoercePath));

		private static object CoercePath(DependencyObject d, object baseValue)
		{
			var self = (BreadCrumbs) d;
			var newValue = (string) baseValue;
			return self.JoinPath(self.SplitPath(newValue));
		}

		private static void OnPathChanged(DependencyObject d, DependencyPropertyChangedEventArgs eventArgs)
		{
			var self = (BreadCrumbs) d;
			var newValue = (string) eventArgs.NewValue;
			self.Components.Clear();
			foreach (var indexComponentPair in self.SplitPath(newValue).Select((component, index) => new KeyValuePair<int, string>(index, component)))
			{
				self.Components.Add(indexComponentPair);
			}
			self.Mode = Mode.BreadCrumbs;
			self.OnPropertyChanged(nameof(Path));
		}

		public string Path
		{
			get { return (string) GetValue(PathProperty); }
			set { SetValue(PathProperty, value); }
		}

		private string JoinPath(IEnumerable<string> components)
		{
			return string.Join(System.IO.Path.DirectorySeparatorChar.ToString(), components.Skip(1));
		}

		private IEnumerable<string> SplitPath(string path)
		{
			var components = new List<string> {"This Computer"};
			path = path.TrimEnd();
			path = path.EndsWith(System.IO.Path.DirectorySeparatorChar.ToString()) ? path.Substring(0, path.Length - 1) : path;
			components.AddRange(path.Split(new[]{ System.IO.Path.DirectorySeparatorChar }, StringSplitOptions.RemoveEmptyEntries));
			return components;
		}

		public BreadCrumbs()
		{
			Components = new ObservableCollection<KeyValuePair<int, string>>();
			Path = "";
			InitializeComponent();
		}

		public BreadCrumbs(string path)
		{
			Path = path;
		}

		private void OnComponentClick(object sender, RoutedEventArgs e)
		{
			var index = (int)((Button) sender).Tag;
			var list = Components;
			for(int i = list.Count - 1; i >= index + 1; i--)
			{
				list.RemoveAt(i);
			}
			OnPropertyChanged(nameof(Path));
		}

		private void OnEditPathClick(object sender, RoutedEventArgs e)
		{
			Mode = Mode.Editing;
			EditPathTextBox.Focus();
		}

		private void OnLostFocusTextBox(object sender, KeyboardFocusChangedEventArgs e)
		{
			var bindingExpression = BindingOperations.GetBindingExpression((TextBox)sender, TextBox.TextProperty);
			bindingExpression?.UpdateTarget();
			Mode = Mode.BreadCrumbs;
		}


		private void OnKeyPressedDown(object sender, KeyEventArgs e)
		{
			var bindingExpression = BindingOperations.GetBindingExpression((TextBox)sender, TextBox.TextProperty);
			if (e.Key == Key.Enter)
			{
				bindingExpression?.UpdateSource();
				Mode = Mode.BreadCrumbs;
			}
			if(e.Key == Key.Escape)
			{
				bindingExpression?.UpdateTarget();
				Mode = Mode.BreadCrumbs;
			}
		}

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}

		private void PathEditorLostFocus(object sender, RoutedEventArgs e)
		{
			Mode = Mode.BreadCrumbs;
		}
	}

	public class ModeToVisibilityConverter : IValueConverter
	{
		public static readonly ModeToVisibilityConverter Default = new ModeToVisibilityConverter();

		public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
		{
			var activeMode = (Mode) value;
			var visibleMode = (Mode) parameter;
			return activeMode == visibleMode ? Visibility.Visible : Visibility.Hidden;
		}

		public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
		{
			throw new NotImplementedException();
		}
	}
}
```

**Comment by JohanLarsson** [comment]
Closing this, could not create a good repro. Sprayed some nullchecks over the code.
